FROM ubuntu:18.04
MAINTAINER Roseline <guseod24@gmail.com>

RUN apt-get update
RUN apt-get install -y nginx
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf #1
RUN chown -R www-data:www-data /var/lib/nginx #2


VOLUME ["/data", "/etc/nginx/site-enabled", "/var/log/nginx"]

# Open HTTP port for nginx
EXPOSE 80

WORKDIR /etc/nginx

CMD ["nginx"]
